### PR TITLE
Refs #33 - add slick database libraries

### PR DESCRIPTION
**Pull request by lightvector**
For the moment, just adds the libraries and a config that establishes an in-memory h2 database. In-memory is not what we want long-term, obviously, but it's convenient for testing.

More database stuff to follow.

### CODE REVIEW

**Comment by lightvector** [comment]
Okay, we now have a database-backed chat server with multiple channels. And I now understand how to do a lot of what we will need to make a real-time game-playing engine go.

@mattj256 - Any comments before I merge? Do you feel you can usefully review things here?

**Comment by mattj256** [comment]
> Any comments before I merge? Do you feel you can usefully review things here?

@lightvector Can you give me an example of a few use cases?
I think the best thing is to write some automated tests to verify expected behavior.
The second-best thing is put a README somewhere (on the wiki?) that explains for simpletons like me how it's supposed to work.

I can kind-of-sort-of figure out the API from reading the code, but I think this kind of documentation would be useful for any programmer joining the team, not just me.

**Comment by mattj256** [comment]
I mean a high-level description of the API that's actually implemented, as opposed to your planned API.

Don't worry about documenting implementation details.

**Comment by lightvector** [comment]
Testing is actually a good thing to bring up. Are there standard practices for testing parts of server infrastructure that are about parsing http requests, or that depend on a database, or that interface with the world in other similar ways?

For now, yes, I can provide an in-repo summary of what's actually implemented as I implement it. This week I need to work primarily on drafting the challenge paper (possibly shooting for meeting a deadline in 2-3 weeks for submissions for an edition the IGCA journal), but I can do this next weekend and then begin work on the main game-playing query handling. I think it will be fairly straightforward now that I know how stuff works.

Any further comments or objections to merge? Should I write the doc first?

**Comment by lightvector** [comment]
By the way, thanks for being around to point out things and give feedback. It's really helpful! :)

**Comment by mattj256** [comment]
> Are there standard practices for testing

What you're describing is integration testing.  (Testing the interconnections between various components.)  There's also unit testing.  (Testing an individual component in isolation, which is what I've done so far.)  There are books written on this.  Researching testing tools is a (potential) project, just like all the research you've already done for Scalatra and the datatabase.  (Researching tools shouldn't hold up this pull request.)

> I can provide an in-repo summary of what's actually implemented as I implement it.

Hmm I think ScalaDoc would be best for this.  It's good to have SOME documentation about what's implemented, and the less overhead in creating and maintaining it the better.  In-repo documentation doesn't really help the people who need it.  They need a flat file, a wiki, a webpage, or something external to the repo.

> Any further comments or objections to merge? Should I write the doc first?

Let me have until Tuesday evening to kick the tires?  I doubt I'll find anything important, but I haven't made time for this yet.

I'll ask you to not merge it in until you have SOME external documentation of how it works and how it's supposed to be used.  That could be a flat file, a wiki, ScalaDoc, whatever is easiest.  One or two sentences per API method is plenty.  Or you could whip up a few simple Perl/shell scripts that test the functionality.  (Testing is more important than documentation, and tests are "sort of" documentation.)

> By the way, thanks for being around to point out things and give feedback. It's really helpful! :)

You're welcome.  Thank you too - it's hard to be motivating doing this alone!!

**Comment by mattj256** [comment]
Ok I finally read through everything.  Geez, you did a lot of work on this!
1. I made my comments per commit instead of per file, which was probably a mistake.
2. I wasn't able to test it.  Based on ChatServlet line 77 I tried this:

```
$ curl -i -H "Content-Type: application/json" -X POST -d '{"username":"Bob"}' http://localhost:8080/chat/login
HTTP/1.1 404 Not Found
Date: Wed, 01 Jul 2015 02:07:54 GMT
Content-Type: application/json; charset=ISO-8859-1
Content-Length: 122
Server: Jetty(9.2.1.v20140609)

Requesting "POST /chat/login" on servlet "" but only have: <ul><li>GET /</li><li>POST /test</li><li>POST /test2</li></ul>
```

I have no idea if this is my error or your error.
1. I'm changing my mind from my previous post - as long as it runs correctly in local testing you should check it in.  This is a large changeset and we can always test it later.  (But I do want to talk about how to test it!)
2. Most of my comments were stylistic.  I don't understand the code well enough to know if you made any bugs.  (Another argument for testing.)

**Comment by mattj256** [comment]
Ok now I understand.
ArimaaServlet works correctly.

ChatServlet is mounted on api/chat, but the inline comments have the wrong URL.

```
$ curl -i -H "Content-Type: application/json" -X POST -d '{"username":"Bob"}' http://localhost:8080/api/chat/login
HTTP/1.1 405 Method Not Allowed
Date: Wed, 01 Jul 2015 02:21:02 GMT
Content-Type: application/json; charset=UTF-8
Allow: GET, HEAD
Content-Length: 0
Server: Jetty(9.2.1.v20140609)
```

I'll leave it up to you whether you fix this before or after you merge.

**Comment by lightvector** [comment]
I pushed cleanups. Thanks for your feedback!
I added a wiki page:

https://github.com/lightvector/arimaa-server/wiki/Arimaa-Game-Server-JSON-API-(implemented)

I'll go ahead and merge this. If you have further comments that need fixes (or if you strongly object to the memory-leaky test I noted in issue #49 ), I'll address them with a new pull request.

**Comment by mattj256** [comment]
Looks fine.  I don't have energy to go line by line over everything all over again.  (Sorry, I have enough energy to look at your stuff but not enough energy to write my stuff.)  If there's any major problems I'm sure we'll find them once people start using the code.  The memory leak is a good thing to investigate but I'm not going to lose sleep over it.  (I think it's a bigger problem for testing than it is for production.)

**Comment by lightvector** [comment]
Sounds good. I'm very busy with paper this week and likely next weekend, but as soon as that's done, I'm going to implement all the game-playing queries. Soon!

**Pull request merged**
