### PR TITLE
Fixes #9: Finish sketching basic board types

### LINKED ISSUE #9: Create internal board representation

### PR DESCRIPTION
**Pull request by lightvector**
@mattj256 - I left a bunch of TODOs in places that might be good starting points for you to jump in.

Comments welcome. My thought for the design is that
1. Board.step should make a step while implementing basic legality checking that doesn't depend on history (# steps left, contents of src and dest, rabbits restrictions, freezing, etc.). 
2. StandardNotation.read runs in a loop: consume next token -> parse step from token -> call Board.step -> call Board.resolveCaps -> if caps did occur, consume next token and check that it's a capture -> repeat. And then at the end call Board.endTurn.
3. Game.parseAndMakeMove calls StandardNotation.read and applies the final checks of whether the position changed or not and 3x repetition.

If you think alternate designs are preferable, particularly as you begin coding and seeing what you run into, we can certainly change things.

### CODE REVIEW

**Comment by thomastanck** [comment]
The design seems good to me.

I'd like to clarify point 3: Game.parseAndMakeMove calls Notation.read, which can be any type of Notation that is implemented. The caller has to call Game.parseAndMakeMove with their desired instance of Notation. (I got nervous when you wrote that it called _Standard_Notation.read)

**Comment by mattj256** [comment]
@lightvector I merged in brendanator's pull request which renamed files from src/scala to src/main/scala.  Welcome to the fun and exciting world of merge conflicts!
Fortunately brenanator didn't make any changes to the files, he just moved them.

```
git checkout iss9
git pull
git status    # shows which files have merge conflicts

# repeat for each file with conflicts
git mv src/scala/Foo.scala src/main/scala/Foo.scala

git add src/main/scala   # tells git that the conflicts have been resolved.
git status     # should be good now
git commit
```

**Comment by lightvector** [comment]
@mattj256 - I'm going ahead and merging this into master so as not to block you from getting started on the movement and legality logic. If you feel strongly about the naming issue you commented on, that (or anything else I've written so far in this branch) is certainly available to be modified.

Thanks!

**Comment by mattj256** [comment]
Thanks @lightvector 
Ok now I have no excuse for not working on this.
I'll be in touch when I have intelligent questions to ask.

**Pull request merged**
