### PR TITLE
Fixes #38: Replace org.playarimaa.util.Result with scala.util.Try

### LINKED ISSUE #38: Replace org.playarimaa.util.Result with scala.util.Try
Scala has a built-in monadic class scala.util.Try.
It is a case class and the types are Success or Failure.
(I hope I'm getting the terminology right!)

This class integrates with Scala's exception handling.  (If an exception is thrown it returns Failure and a message, otherwise Success.)

### PR DESCRIPTION
**Pull request by mattj256**
@lightvector 
I know the Board/Move is on the critical path but I needed something a little easier to work on.

After making my changes I reran the unit tests and made sure localhost:8080 came up correctly.
This is hardly exhaustive but it's a lot better than nothing.

Some things to note:
- `Success()` gave compile warnings so I changed to `Success(())`
- I created a new Exception class that is intended to be the root of the hierarchy.  It's totally legal to just return Failure, but I'm used to Java and that seemed like the familiar way to do it.
- similarly I did `throw new XxxException` rather than explicitly returning Failure.

I think we should standardize - either return Failure or throw an exception, but do it the same way every time.

### CODE REVIEW

**Comment by lightvector** [comment]
Cool. One detail though - you should definitely return Failure rather than throw an exception. Because throwing an exception will actually throw the exception. That is, the function will either return Success(...) or throw an exception, and it will never return Failure(...).

The way that Try normally integrates with the exception handling is that if you write Try(...some code here...), then it will catch exceptions raised in that block of code, which is convenient.

**Comment by mattj256** [comment]
For some reason I thought that what I did would return a Failure object even though that doesn't really make sense.  I'll fix it up and resubmit.

**Comment by mattj256** [comment]
Is this good?  The parameter to Failure is a Throwable so I didn't throw the exceptions but I still had to create them.  I'm way too new at this to know if I'm doing it the "right" way or not.

**Comment by lightvector** [comment]
Good!

**Pull request merged**
