### PR TITLE
Patches for issue #14 - cleaning up build file and minor other changes

### PR DESCRIPTION
**Pull request by lightvector**
@mattj256: I'll not bother to revert and recommit the other change, but I went and cleaned up the things you suggested.

### CODE REVIEW

**Comment by lightvector** [comment]
How does one make this reference issue #14 so that something appears in that thread?

**Comment by mattj256** [comment]
In the commit message if you put "#14" (no quotes) it will reference that issue.
If you put "Fixes #14" (no quotes) in the commit message, then when it gets merged into master GitHub will automatically close the associated issue.
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by mattj256** [comment]
My suggested changes are minor.
Up to you whether you want to merge as is, make changes and merge, or make changes and resubmit to me.

**Comment by lightvector** [comment]
Thanks for the review and help! :)

**Pull request merged**
