### PR TITLE
Refs #3, refs #9: adding class representing an Arimaa playing piece.

### PR DESCRIPTION
**Pull request by mattj256**
Hi @lightvector 
Works fine.
1. #3 Package structure?  I own dreamsmadevisible.com.  I'm happy to use something else.
2. I just want to make a simple Java enum and there are too many options.  I don't know if I chose the "right" one.
3. This is going to be horribly inefficient; down the road we should use bitboards.

### CODE REVIEW

**Comment by lightvector** [comment]
I'd be happy with using that domain for the package. Is only the fact that we don't have a domain yet for the website/gameserver yet that makes you want to use this one, or is it that you would prefer not to have the package domain tied to the specific site that we happen run the server on?

If the former, then we should just get a domain.

**Comment by mattj256** [comment]
@lightvector the first one.
I think the package/namespace for our source code should match the website of the server.
I think you should buy a domain.. let me know when that's done and I'll update my code to match.
Please leave a short comment in #3 about what package structure you want.  I like com.example.arimaa.server, so we have flexibility to add other modules down the road.

**Comment by lightvector** [comment]
Motivated by what you brought up for (2), I did some research. I agree, having a direct and clear way to do enums is not one of Scala's strong points.

This is the best reference I can find.
http://stackoverflow.com/questions/1898932/case-objects-vs-enumerations-in-scala

I suspect the "sealed trait" plus "case object" pattern will be better here (definitely so for a players enum for "Gold" and "Silver"), due to the pattern matching support. In that case, we do need to repeat ourselves slightly to define a "values" or "all" field that's a list containing all of the pieces. But that's the only thing - except for the ability to have a list of all of them to iterate over them, all of the other drawbacks deal with indexing, which I don't think is a big deal here. And we're also not going to be parsing "HORSE_GOLD" from a file, so the built-in string parsing from Enumeration also doesn't help us.

Although for pieces, the difference isn't huge - we might not care overly much about pattern matching on pieces.

Either way, the class or trait should be sealed - there's no reason to be creating these on the fly (which gets rid of the performance concerns too). I suspect we will want additional properties of these pieces as well (player, is_rabbit), which definitely means we don't want code in other classes to be creating these on the fly (in the process having to get all the fields set correctly).

**Comment by mattj256** [comment]
@lightvector yes I keep reading about "sealed traits" and that's beyond my level right now.
I'm just changing the package and I'll let you make whatever changes you think are best.

**Comment by mattj256** [comment]
@lightvector 
Ok this is ready.
Can we close #3 ?

**Pull request merged**
